proxies:
  - name: "WG-KR"
    type: wireguard
    server: 220.126.35.55
    port: 42723
    ip: 10.254.3.20
    private-key: ODXUjB87Uuwcmg0Xj1liiRDnQRZdF+vXNlTtfBj7cHc=
    public-key: L0P5zYLVCgRZKxgHTRDLhdfcNIdFML84D6U8RCtnez0=
    allowed-ips: ['0.0.0.0/0']
    persistent-keepalive: 25
    mtu: 1420
    dns:
      - 168.126.63.1
      - 168.126.63.2
      - 210.220.163.82

proxy-groups:
  - name: "🚀 节点选择"
    type: select
    proxies:
      - "WG-KR"
      - "DIRECT"

rules:
  - MATCH,🚀 节点选择
